function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -100; // player
	global.__objectDepths[1] = 0; // wall
	global.__objectDepths[2] = -99; // body
	global.__objectDepths[3] = -100; // eyes
	global.__objectDepths[4] = -100; // hair
	global.__objectDepths[5] = 0; // npc_warrior
	global.__objectDepths[6] = 0; // skills_jobs
	global.__objectDepths[7] = -1; // barsdraw
	global.__objectDepths[8] = -102; // frame
	global.__objectDepths[9] = 0; // log_move
	global.__objectDepths[10] = -1000; // log_char
	global.__objectDepths[11] = 0; // log_str
	global.__objectDepths[12] = 0; // apoint
	global.__objectDepths[13] = 0; // log_dex
	global.__objectDepths[14] = 0; // log_int
	global.__objectDepths[15] = 0; // log_luk
	global.__objectDepths[16] = -1000; // log_okchar
	global.__objectDepths[17] = -101; // top
	global.__objectDepths[18] = 1; // bars_skills
	global.__objectDepths[19] = 0; // skills_bespeed
	global.__objectDepths[20] = 0; // aaq
	global.__objectDepths[21] = -1000; // log_load
	global.__objectDepths[22] = 0; // monster1
	global.__objectDepths[23] = 0; // monster_wall
	global.__objectDepths[24] = -102; // weapon
	global.__objectDepths[25] = 0; // effect
	global.__objectDepths[26] = 0; // ap_ap
	global.__objectDepths[27] = -101; // portaln
	global.__objectDepths[28] = 0; // watch
	global.__objectDepths[29] = 0; // npc_fight
	global.__objectDepths[30] = 0; // monster2
	global.__objectDepths[31] = 0; // npc_gomon
	global.__objectDepths[32] = 0; // monster3
	global.__objectDepths[33] = 0; // wall2
	global.__objectDepths[34] = -101; // portalb
	global.__objectDepths[35] = 0; // right_eye
	global.__objectDepths[36] = 0; // left_eye
	global.__objectDepths[37] = -1000; // logo_okchar1
	global.__objectDepths[38] = 0; // right_hair
	global.__objectDepths[39] = 0; // left_hair
	global.__objectDepths[40] = 0; // monster4
	global.__objectDepths[41] = 0; // apapstr
	global.__objectDepths[42] = 0; // apapdex
	global.__objectDepths[43] = 0; // apapint
	global.__objectDepths[44] = 0; // apapluk
	global.__objectDepths[45] = 0; // right_hairc
	global.__objectDepths[46] = 0; // left_hairc
	global.__objectDepths[47] = 0; // right_bodyc
	global.__objectDepths[48] = 0; // left_bodyc
	global.__objectDepths[49] = 0; // right_top
	global.__objectDepths[50] = 0; // left_top
	global.__objectDepths[51] = 0; // apap2str
	global.__objectDepths[52] = 0; // apap2dex
	global.__objectDepths[53] = 0; // apap2int
	global.__objectDepths[54] = 0; // apap2luk
	global.__objectDepths[55] = 0; // top1d
	global.__objectDepths[56] = 0; // thplace
	global.__objectDepths[57] = 0; // top1pr
	global.__objectDepths[58] = 0; // top2d
	global.__objectDepths[59] = 0; // top2pr
	global.__objectDepths[60] = 0; // skwar_att
	global.__objectDepths[61] = 0; // skills_watt
	global.__objectDepths[62] = 0; // haircardD
	global.__objectDepths[63] = 0; // haircardpr
	global.__objectDepths[64] = 0; // npc_gachufon
	global.__objectDepths[65] = 0; // hairoomcont
	global.__objectDepths[66] = -1000; // hairoomselect
	global.__objectDepths[67] = 0; // npc_rogue
	global.__objectDepths[68] = 0; // npc_bowman
	global.__objectDepths[69] = 1; // bars_items
	global.__objectDepths[70] = 0; // monster5
	global.__objectDepths[71] = -100; // buttom
	global.__objectDepths[72] = 0; // skro_shadow
	global.__objectDepths[73] = -98; // shadow
	global.__objectDepths[74] = 0; // skills_rshadow
	global.__objectDepths[75] = 0; // monster6
	global.__objectDepths[76] = 0; // bottom2d
	global.__objectDepths[77] = 0; // bottom2th
	global.__objectDepths[78] = 0; // weapon2d
	global.__objectDepths[79] = 0; // weapon2th
	global.__objectDepths[80] = 0; // bottom1th
	global.__objectDepths[81] = 0; // bottom1d
	global.__objectDepths[82] = 0; // weapon1d
	global.__objectDepths[83] = 0; // weapon1th
	global.__objectDepths[84] = 0; // obj_textfield
	global.__objectDepths[85] = 0; // skro_bigstar
	global.__objectDepths[86] = 0; // skills_rbigs
	global.__objectDepths[87] = 0; // skills_r6att
	global.__objectDepths[88] = 0; // skro_6att
	global.__objectDepths[89] = 0; // hpuperd
	global.__objectDepths[90] = 0; // hpuperpr
	global.__objectDepths[91] = 0; // monster7
	global.__objectDepths[92] = 0; // top3d
	global.__objectDepths[93] = 0; // top3pr
	global.__objectDepths[94] = 0; // top4d
	global.__objectDepths[95] = 0; // top4pr
	global.__objectDepths[96] = 0; // monster8
	global.__objectDepths[97] = 0; // weapon3d
	global.__objectDepths[98] = 0; // weapon3th
	global.__objectDepths[99] = 0; // skills_whealt
	global.__objectDepths[100] = 0; // skwar_healt
	global.__objectDepths[101] = 0; // weapon4d
	global.__objectDepths[102] = 0; // weapon4th
	global.__objectDepths[103] = 0; // right_hair2
	global.__objectDepths[104] = 0; // left_hair2
	global.__objectDepths[105] = 0; // weapon5th
	global.__objectDepths[106] = 0; // weapon5d
	global.__objectDepths[107] = -101; // portalend
	global.__objectDepths[108] = -101; // portalgend
	global.__objectDepths[109] = 0; // moneyd


	global.__objectNames[0] = "player";
	global.__objectNames[1] = "wall";
	global.__objectNames[2] = "body";
	global.__objectNames[3] = "eyes";
	global.__objectNames[4] = "hair";
	global.__objectNames[5] = "npc_warrior";
	global.__objectNames[6] = "skills_jobs";
	global.__objectNames[7] = "barsdraw";
	global.__objectNames[8] = "frame";
	global.__objectNames[9] = "log_move";
	global.__objectNames[10] = "log_char";
	global.__objectNames[11] = "log_str";
	global.__objectNames[12] = "apoint";
	global.__objectNames[13] = "log_dex";
	global.__objectNames[14] = "log_int";
	global.__objectNames[15] = "log_luk";
	global.__objectNames[16] = "log_okchar";
	global.__objectNames[17] = "top";
	global.__objectNames[18] = "bars_skills";
	global.__objectNames[19] = "skills_bespeed";
	global.__objectNames[20] = "aaq";
	global.__objectNames[21] = "log_load";
	global.__objectNames[22] = "monster1";
	global.__objectNames[23] = "monster_wall";
	global.__objectNames[24] = "weapon";
	global.__objectNames[25] = "effect";
	global.__objectNames[26] = "ap_ap";
	global.__objectNames[27] = "portaln";
	global.__objectNames[28] = "watch";
	global.__objectNames[29] = "npc_fight";
	global.__objectNames[30] = "monster2";
	global.__objectNames[31] = "npc_gomon";
	global.__objectNames[32] = "monster3";
	global.__objectNames[33] = "wall2";
	global.__objectNames[34] = "portalb";
	global.__objectNames[35] = "right_eye";
	global.__objectNames[36] = "left_eye";
	global.__objectNames[37] = "logo_okchar1";
	global.__objectNames[38] = "right_hair";
	global.__objectNames[39] = "left_hair";
	global.__objectNames[40] = "monster4";
	global.__objectNames[41] = "apapstr";
	global.__objectNames[42] = "apapdex";
	global.__objectNames[43] = "apapint";
	global.__objectNames[44] = "apapluk";
	global.__objectNames[45] = "right_hairc";
	global.__objectNames[46] = "left_hairc";
	global.__objectNames[47] = "right_bodyc";
	global.__objectNames[48] = "left_bodyc";
	global.__objectNames[49] = "right_top";
	global.__objectNames[50] = "left_top";
	global.__objectNames[51] = "apap2str";
	global.__objectNames[52] = "apap2dex";
	global.__objectNames[53] = "apap2int";
	global.__objectNames[54] = "apap2luk";
	global.__objectNames[55] = "top1d";
	global.__objectNames[56] = "thplace";
	global.__objectNames[57] = "top1pr";
	global.__objectNames[58] = "top2d";
	global.__objectNames[59] = "top2pr";
	global.__objectNames[60] = "skwar_att";
	global.__objectNames[61] = "skills_watt";
	global.__objectNames[62] = "haircardD";
	global.__objectNames[63] = "haircardpr";
	global.__objectNames[64] = "npc_gachufon";
	global.__objectNames[65] = "hairoomcont";
	global.__objectNames[66] = "hairoomselect";
	global.__objectNames[67] = "npc_rogue";
	global.__objectNames[68] = "npc_bowman";
	global.__objectNames[69] = "bars_items";
	global.__objectNames[70] = "monster5";
	global.__objectNames[71] = "buttom";
	global.__objectNames[72] = "skro_shadow";
	global.__objectNames[73] = "shadow";
	global.__objectNames[74] = "skills_rshadow";
	global.__objectNames[75] = "monster6";
	global.__objectNames[76] = "bottom2d";
	global.__objectNames[77] = "bottom2th";
	global.__objectNames[78] = "weapon2d";
	global.__objectNames[79] = "weapon2th";
	global.__objectNames[80] = "bottom1th";
	global.__objectNames[81] = "bottom1d";
	global.__objectNames[82] = "weapon1d";
	global.__objectNames[83] = "weapon1th";
	global.__objectNames[84] = "obj_textfield";
	global.__objectNames[85] = "skro_bigstar";
	global.__objectNames[86] = "skills_rbigs";
	global.__objectNames[87] = "skills_r6att";
	global.__objectNames[88] = "skro_6att";
	global.__objectNames[89] = "hpuperd";
	global.__objectNames[90] = "hpuperpr";
	global.__objectNames[91] = "monster7";
	global.__objectNames[92] = "top3d";
	global.__objectNames[93] = "top3pr";
	global.__objectNames[94] = "top4d";
	global.__objectNames[95] = "top4pr";
	global.__objectNames[96] = "monster8";
	global.__objectNames[97] = "weapon3d";
	global.__objectNames[98] = "weapon3th";
	global.__objectNames[99] = "skills_whealt";
	global.__objectNames[100] = "skwar_healt";
	global.__objectNames[101] = "weapon4d";
	global.__objectNames[102] = "weapon4th";
	global.__objectNames[103] = "right_hair2";
	global.__objectNames[104] = "left_hair2";
	global.__objectNames[105] = "weapon5th";
	global.__objectNames[106] = "weapon5d";
	global.__objectNames[107] = "portalend";
	global.__objectNames[108] = "portalgend";
	global.__objectNames[109] = "moneyd";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
